apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-pod-access-role
  namespace: dev-agumon
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]



---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-pod-access-role
  namespace: stage-agumon
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
