apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-pod-access-role-binding-stage-agumon
  namespace: dev-agumon
subjects:
- kind: ServiceAccount
  name: agumon
  namespace: dev-agumon
- kind: ServiceAccount
  name: agumon
  namespace: stage-agumon
roleRef:
  kind: Role
  name: full-pod-access-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-pod-access-role-binding-stage-agumon
  namespace: stage-agumon
subjects:
- kind: ServiceAccount
  name: agumon
  namespace: dev-agumon
- kind: ServiceAccount
  name: agumon
  namespace: stage-agumon
roleRef:
  kind: Role
  name: full-pod-access-role
  apiGroup: rbac.authorization.k8s.io
